// {
// path: '/home',
// name: 'Home',
// component: Home,
// meta :{ role : ["超级管理员","管理员","主任"] },
// children:[
//   {
//     path: '',
//     name: 'workday',
//     component: Workday,
//     meta :{ role : ["超级管理员","管理员","主任"] },
//   },
// {
//   path: 'main',
//   name: 'main',
//   component: Main,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'workday',
//   name: 'workday',
//   component: Workday,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'perScore',
//   name: 'score',
//   component: Score,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'perDetails',
//   name: 'details',
//   component: Details,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'tecScore',
//   name: 'tecScore',
//   component: TecScore,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'tecDetails',
//   name: 'tecDetails',
//   component: TecDetails,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'personal',
//   name: 'personal',
//   component: Personal,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'department',
//   name: 'department',
//   component: Department,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'appraiseManage',
//   name: 'appraiseManage',
//   component: AppraiseManage,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'adminProject',
//   name: 'adminProject',
//   component: AdminProject,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'plannedPublicTask',
//   name: 'plannedPublicTask',
//   component: PlannedPublicTask,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
// {
//   path: 'roleManage',
//   name: 'roleManage',
//   component: RoleManage,
//   meta :{ role : ["超级管理员","管理员","主任"] },
// },
